name: 'Build and Push to Docker Hub'
on:
  push:
    branches:
      - master
  pull_request:
env:
  IMAGE_NAME: node-slim
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: docker build -t afanyiyu/bilibili-vtuber-live-danmaku-relay github.com/dd-center/bilibili-vtuber-live-danmaku-relay
      - name: Log In
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push
        run: docker push afanyiyu/bilibili-vtuber-live-danmaku-relay
